config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  scope :api, module: 'api' do
    resources :subscriptions, only: [:create, :destroy]
  end

  resources :questions, only: [:index, :show, :new, :create]
  resources :answers, only: :create

  root to: 'home#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :question

  validates :content, :question, presence: true

  after_create :send_broadcast
  after_create :push_notification

  private

  def send_broadcast
    ActionCable.server.broadcast "answers_#{question.id}", id: id, content: content
  end

  def push_notification
    PushNotificationJob.perform_later(question)
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/question.rb
class Question < ApplicationRecord
  has_many :answers

  validates :content, presence: true

  after_create :send_broadcast

  private

  def send_broadcast
    ActionCable.server.broadcast 'questions', id: id, content: content
  end
end

app/models/subscription.rb
class Subscription < ApplicationRecord
  validates :subscription_id, :subscription_path, :endpoint, :key_p256dh, :key_auth, presence: true
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
  def create
    answer = Answer.new(permitted_attributes)
    answer.save!

    redirect_to question_path(answer.question)
  end

  private

  def permitted_attributes
    params
      .require(:answer)
      .permit(:content, :question_id)
  end
end

app/controllers/api/base_controller.rb
module Api
  class BaseController < ApplicationController
    protect_from_forgery with: :null_session
  end
end

app/controllers/api/subscriptions_controller.rb
module Api
  class SubscriptionsController < BaseController
    def create
      subscription = Subscription.new(permitted_attributes)
      subscription.save!

      head :ok
    end

    def destroy
      subscription = Subscription.find_by(subscription_id: params[:id])
      subscription.destroy!

      head :ok
    end

    private

    def permitted_attributes
      params.permit(:subscription_id, :subscription_path, :key_auth, :key_p256dh, :endpoint)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  def index
    @questions = Question.all
  end

  def show
    @question = Question.includes(:answers).find(params[:id])
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new(permitted_attributes)

    if @question.save
      redirect_to questions_path, notice: 'Question was successfully created'
    else
      render :new
    end
  end

  private

  def permitted_attributes
    params.require(:question).permit(:content)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.slim
h2 Nimbl3 growth

h2 Navigator
= link_to 'Questions', questions_path

h2 Description

p
  | The main idea is create a simple Q&A app, have some features
  ul
    li <b>Real time</b> update questions list, answer of a question if user stay on website
    li <b>Push notification</b> to user, when user is subscription

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | Question Answer
    = csrf_meta_tags
    = action_cable_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
    | <link rel="manifest" href="/manifest.json">
  body
    = yield
    hr
    h2 Subscription
    button.toggle-push-element

app/views/questions/_answer.html.slim
li
  = "#{answer.id} - #{answer.content}"

app/views/questions/_form.html.slim
= form_for resource do |f|
  = f.text_field :content
  br
  = f.submit

app/views/questions/_question.html.slim
.question
  = link_to "#{question.id} - #{question.content}", question_path(question)

app/views/questions/index.html.slim
= link_to 'Home', root_path
br
= link_to 'Create questions', new_question_path

h2 Questions
div.questions
  = render partial: 'question', collection: @questions

app/views/questions/new.html.slim
h2 Navigator
= link_to 'Home', root_path
h2 Create new question
= render 'form', resource: @question

app/views/questions/show.html.slim
= link_to 'Home', root_path
br
= link_to 'Questions', questions_path

h2 Question
= @question.content

h2 Answers

ul#answers
  = render partial: 'answer', collection: @question.answers

= form_for @question.answers.new do |f|
  = f.hidden_field :question_id
  = f.text_field :content
  br
  = f.submit